# Generated by Django 2.1.7 on 2020-04-23 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0005_auto_20200214_1248'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('Accounts', '0002_delevryman'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DelevryMan',
            new_name='DeleveryPerson',
        ),
    ]
