# Generated by Django 2.1.7 on 2020-05-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('admin', '0005_auto_20200214_1248'),
        ('Accounts', '0003_auto_20200423_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeleveryPerson',
            new_name='DeliveryPerson',
        ),
    ]
